/**:
  ros__parameters:
    namespace: "camera1"
    video_device: "/dev/video0"
    framerate: 30.0
    pixel_format: "mjpeg2rgb"
    io_method: "mmap"
    image_width: 640
    image_height: 480

    camera_name: "test_camera"

